common:
  fp16: true
  log_format: json
  log_interval: 200
  seed: 1337
  tensorboard_logdir: tblog

checkpoint:
  save_interval_updates: 2000
  keep_interval_updates: 5
  keep_best_checkpoints: 10
  no_epoch_checkpoints: true

distributed_training:
  ddp_backend: no_c10d
  distributed_backend: 'gloo'
  distributed_world_size: 1
  distributed_port: 29671
  nprocs_per_node: 1
  find_unused_parameters: true

task:
  _name: contentvec_pretraining
  data: 'data\metadata'
  label_dir: 'data\label'
  labels: ["km"]
  label_rate: ${model.label_rate}
  sample_rate: 16000
  max_sample_size: 250000
  min_sample_size: 32000
  pad_audio: false
  random_crop: true
  crop: true
  normalize: false # must be consistent with extractor
  spk2info: data\spk2info.dict

dataset:
  num_workers: 10
  max_tokens: 900000
  skip_invalid_size_inputs_valid_test: true
  validate_interval: 5
  validate_interval_updates: 10000
  train_subset: 'train'
  valid_subset: 'valid'

criterion:
  _name: contentvec
  pred_masked_weight: 1.0
  pred_nomask_weight: 0.0
  loss_weights: [10, 1e-5]

optimization:
  max_update: 1000000
  lr: [0.0005]
  clip_norm: 10.0
  update_freq: [2]

optimizer:
  _name: adam
  adam_betas: (0.9,0.98)
  adam_eps: 1e-06
  weight_decay: 0.01
  update_freq: [1]
  max_update: 1000000

lr_scheduler:
  _name: polynomial_decay
  warmup_updates: 8000

model:
  _name: contentvec
  label_rate: 50
  skip_masked: false
  skip_nomask: false
  mask_prob: 0.80
  extractor_mode: default
  conv_feature_layers: '[(512,10,5)] + [(512,3,2)] * 4 + [(512,2,2)] * 2'
  final_dim: 256
  encoder_layerdrop: 0.05
  dropout_input: 0.1
  dropout_features: 0.1
  dropout: 0.1
  attention_dropout: 0.1
  feature_grad_mult: 0.1
  untie_final_proj: true
  activation_dropout: 0.0
  encoder_layers_1: 3
  logit_temp_ctr: 0.1
  ctr_layers: [-6]

hydra:
  job:
    config:
      override_dirname:
        kv_sep: '-'
        item_sep: '__'
        exclude_keys:
          - run
          - task.data
          - task.label_dir
  run:
    dir: ???
  sweep:
    dir: ???
    subdir: ${hydra.job.config_name}__${hydra.job.override_dirname}